# Generated by Django 3.2.13 on 2023-02-26 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent_ally', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posting',
            new_name='Post',
        ),
    ]
